### PR TITLE
Changing join function to remove '\\' from paths

### LINKED ISSUE #11: Error using S3 with Digital Ocean space
I'm using the repo https://github.com/rafas/test-attachments with a digital ocean space and the 1.3.1 release, and when i try to upload any image, i got this error:

#### [1658595602786] ERROR (test-attachments/10228 on Chuya-Sekira): E_CANNOT_READ_FILE: Cannot read file from location

```json
err: {
      "type": "CannotReadFileException",
      "message": "E_CANNOT_READ_FILE: Cannot read file from location \"image_upload_tmp\\cl5y5bn9y0001bcxi3h1y3jqi.jpg\"",
      "stack":
          CannotReadFileException: E_CANNOT_READ_FILE: Cannot read file from location "image_upload_tmp\cl5y5bn9y0001bcxi3h1y3jqi.jpg"
              at Function.invoke (D:\Sandbox\test-attachments\node_modules\@adonisjs\drive\build\src\Exceptions\index.js:30:23)
              [...]
              at UploadsController.store (D:\Sandbox\test-attachments\app\Controllers\Http\UploadsController.ts:22:5)
      "location": "image_upload_tmp\\cl5y5bn9y0001bcxi3h1y3jqi.jpg",
      "original": {
        "type": "NoSuchKey",
        "message": "UnknownError",
        "stack":
            NoSuchKey: UnknownError
                at deserializeAws_restXmlNoSuchKeyResponse (D:\Sandbox\test-attachments\node_modules\@aws-sdk\client-s3\dist-cjs\protocols\Aws_restXml.js:8595:23)
                [...]
                at S3Driver.get (D:\Sandbox\test-attachments\node_modules\@adonisjs\drive-s3\build\src\Drivers\S3.js:114:44)
        "name": "NoSuchKey",
        "$fault": "client",
        "$metadata": {
          "httpStatusCode": 404,
          "attempts": 1,
          "totalRetryDelay": 0
        },
        "Code": "NoSuchKey",
        "BucketName": "altab",
        "RequestId": "tx000000000000058b7198e-0062dc2b51-5242291f-fra1b",
        "HostId": "5242291f-fra1b-fra1-zg02"
      }
    }
```

It's different from the previous error, the location was
`      "location": "image_upload_tmp/image_upload_tmp/cl3p71qps0001dgy8ezl0esv4.png",`
and now
`      "location": "image_upload_tmp\\cl5y4zxm10001w4xi1wrr6674.jpg",`

The file is properly uploaded to the space on DO as you can see here:
```xml
<Contents>
<Key>image_upload_tmp/cl5y5bn9y0001bcxi3h1y3jqi.jpg</Key>
<LastModified>2022-07-23T17:09:37.080Z</LastModified>
<ETag>"adabedb0c7ce028fe5915f088c2d3ac7"</ETag>
<Size>579852</Size>
<StorageClass>STANDARD</StorageClass>
<Owner>
<ID>11535310</ID>
<DisplayName>11535310</DisplayName>
</Owner>
<Type>Normal</Type>
</Contents>
```
The key is different from the location, i don't know if it's normal and if not how can i fix it. 

After some research, i modified the join fonction used to create the path on src/index.js
```js
        this.fileName = attributes.fileName ?? '';
        this.path = attributes.path ?? '';
        this.isLocal = !!this.path || !!this.buffer;
        if (attributes.fileName) {
            // this.relativePath = (0, path_1.join)(exports.tempUploadFolder, attributes.fileName);
            this.relativePath = exports.tempUploadFolder + attributes.fileName;
        }
        else if (attributes.name) {
            this.relativePath = (0, path_1.join)(exports.tempUploadFolder, attributes.name);
        }
```
And it's working properly

### PR DESCRIPTION
**Pull request by AT-Lorlando**
## Proposed changes

The join function in TS sometime use ```\\``` to create path, and Digital Ocean Space's doesn't recognize any path with it. Change the join function to a concatenation work properly.

This is to fix #11

### CODE REVIEW

File: src/Attachment/index.ts [hunk 1]
```diff
@@ -317,9 +317,9 @@ export class ResponsiveAttachment implements ResponsiveAttachmentContract {
   }
 
   protected async enhanceFile(): Promise<ImageInfo> {
-    // Read the image as a buffer using `Drive.get()`
-    const originalFileBuffer = this.buffer ?? (await this.getDisk().get(this.relativePath!))
-
+    // Read the image as a buffer using `Drive.get()`, normalizing the path
+    const originalFileBuffer =
+      this.buffer ?? (await this.getDisk().get(this.relativePath!.replace(/\\/g, '/')))
```
Comment (ndianabasi) [inline src/Attachment/index.ts]: Please replace the modified lines with:

```ts
    // Read the image as a buffer using `Drive.get()`
    // Make sure path is normalised
    const originalFileBuffer =
      this.buffer ?? (await this.getDisk().get(normalize(this.relativePath!)))
```

Import `normalize` from `path` at the top-level imports.

**Review by ndianabasi — CHANGES_REQUESTED** [review]

**Review by ndianabasi — APPROVED** [review]
Thanks for the PR. 🙏🏾
